import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useAccountAuth } from '../hooks/useAccountAuth';
import { usePlayerProfile } from '../hooks/usePlayerProfile';
export function AccountPanel() {
    const { user, loading, error, linkWithGoogle, signInGoogle, signOutUser, signInEmail, registerEmail, linkEmail, isAnonymous } = useAccountAuth();
    const { profile } = usePlayerProfile();
    const [email, setEmail] = useState('');
    const [pw, setPw] = useState('');
    const [mode, setMode] = useState('login');
    return (_jsxs("div", { className: "p-4 rounded-2xl bg-[#12171f] border border-white/10 text-sm w-full max-w-md flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "font-semibold", children: "Account" }), user && _jsx("span", { className: "text-[10px] px-2 py-0.5 rounded bg-white/10", children: isAnonymous ? 'Anonymous' : 'Linked' })] }), loading && _jsx("div", { className: "text-xs opacity-60", children: "Loading auth\u2026" }), error && _jsx("div", { className: "text-xs text-red-400", children: error }), _jsxs("div", { className: "text-xs break-all", children: ["UID: ", user ? user.uid : '—', _jsx("br", {}), "Profile: ", profile ? 'Loaded' : '—'] }), _jsxs("div", { className: "flex flex-col gap-2", children: [isAnonymous && (_jsxs(_Fragment, { children: [_jsx("button", { onClick: linkWithGoogle, className: "rounded bg-emerald-600/70 hover:bg-emerald-600 px-3 py-2 text-xs", children: "Link Google" }), _jsx("div", { className: "flex gap-2 text-[11px]", children: _jsx("button", { onClick: signInGoogle, className: "flex-1 rounded bg-white/10 hover:bg-white/15 px-2 py-1", children: "Sign In Google" }) }), _jsxs("div", { className: "flex items-center gap-2 text-[10px] opacity-60", children: [_jsx("span", { children: "Email" }), _jsxs("select", { value: mode, onChange: e => setMode(e.target.value), className: "bg-white/10 rounded px-1 py-0.5", children: [_jsx("option", { value: "login", children: "Login" }), _jsx("option", { value: "register", children: "Register" }), _jsx("option", { value: "link", children: "Link" })] })] }), _jsx("input", { value: email, onChange: e => setEmail(e.target.value), placeholder: "email", className: "px-2 py-1 rounded bg-white/5 border border-white/10 text-xs" }), _jsx("input", { value: pw, type: "password", onChange: e => setPw(e.target.value), placeholder: "password", className: "px-2 py-1 rounded bg-white/5 border border-white/10 text-xs" }), _jsx("button", { onClick: () => mode === 'login' ? signInEmail(email, pw) : mode === 'register' ? registerEmail(email, pw) : linkEmail(email, pw), className: "rounded bg-indigo-600/70 hover:bg-indigo-600 px-3 py-2 text-xs disabled:opacity-40", disabled: !email || !pw, children: mode === 'login' ? 'Sign In Email' : mode === 'register' ? 'Register Email' : 'Link Email' })] })), !isAnonymous && (_jsx("button", { onClick: signOutUser, className: "rounded bg-red-600/70 hover:bg-red-600 px-3 py-2 text-xs", children: "Sign Out" }))] })] }));
}
export default AccountPanel;
